name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v6
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: mozilla-actions/sccache-action@v0.0.11
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: ./script/linux
      - run: cargo fmt --all -- --check
      - run: >
          RUSTC_WRAPPER=sccache
          RUSTFLAGS="-C link-arg=-fuse-ld=lld"
          cargo clippy --all-targets -- -D warnings
      - run: >
          RUSTC_WRAPPER=sccache
          RUSTFLAGS="-C link-arg=-fuse-ld=lld"
          cargo test --verbose
